<?php

namespace ContainerLbjgkJ0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForecast2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AySNhdq.App\Entity\Forecast' shared service.
     *
     * @return \App\Entity\Forecast
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AySNhdq": it needs an instance of "App\\Entity\\Forecast" but this type has been excluded in "config/services.yaml".');
    }
}
