<?php

namespace ContainerLbjgkJ0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherCityCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\WeatherCityCommand' shared autowired service.
     *
     * @return \App\Command\WeatherCityCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'WeatherCityCommand.php';

        $container->privates['App\\Command\\WeatherCityCommand'] = $instance = new \App\Command\WeatherCityCommand(($container->privates['App\\Service\\WeatherUtil'] ?? $container->load('getWeatherUtilService')), ($container->privates['App\\Repository\\CityRepository'] ?? $container->load('getCityRepositoryService')));

        $instance->setName('weather:city');
        $instance->setDescription('Displays a forecast for selected city');

        return $instance;
    }
}
