<?php

namespace ContainerBtA4xIF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jyxuf8oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jyxuf8o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jyxuf8o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'city' => ['privates', '.errored..service_locator.jyxuf8o.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.jyxuf8o": it needs an instance of "App\\Entity\\City" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'city' => 'App\\Entity\\City',
            'entityManager' => '?',
        ]);
    }
}
