<?php

namespace ContainerBtA4xIF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCity2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jyxuf8o.App\Entity\City' shared service.
     *
     * @return \App\Entity\City
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jyxuf8o": it needs an instance of "App\\Entity\\City" but this type has been excluded in "config/services.yaml".');
    }
}
