App\Entity\Forecast:
  properties:
    date:
      - NotBlank:
          message: 'Date should not be blank.'
          groups: [ 'create', 'edit' ]
    temperature:
      - Range:
          min: -100
          max: 80
          invalidMessage: 'Temperature should be a number.'
          notInRangeMessage: 'Temperature should be between -100 and 80 degrees.'
          groups: [ 'create', 'edit' ]
      - NotBlank:
          message: 'Temperature should not be blank.'
          groups: [ 'create', 'edit' ]
    humidity:
      - Range:
          min: 0
          max: 100
          invalidMessage: 'Humidity should be a number.'
          notInRangeMessage: 'Humidity should be between 0% and 100%.'
          groups: [ 'create', 'edit' ]
      - NotBlank:
          message: 'Humidity should not be blank.'
          groups: [ 'create', 'edit' ]
    pressure:
      - Range:
          min: 900
          max: 1100
          invalidMessage: 'Pressure should be a number.'
          notInRangeMessage: 'Pressure should be between 900 and 1100 hPa.'
          groups: [ 'create', 'edit' ]
      - NotBlank:
          message: 'Pressure should not be blank.'
          groups: [ 'create', 'edit' ]
    description:
      - NotBlank:
          message: 'Description should not be blank.'
          groups: [ 'create', 'edit' ]
    city:
      - NotBlank:
          message: 'You should choose a city.'
          groups: [ 'create', 'edit' ]