<?php

namespace Container0xEe0U7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_29QtlAqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.29QtlAq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.29QtlAq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'city' => ['privates', '.errored..service_locator.29QtlAq.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.29QtlAq": it needs an instance of "App\\Entity\\City" but this type has been excluded in "config/services.yaml".'],
            'util' => ['privates', 'App\\Service\\WeatherUtil', 'getWeatherUtilService', true],
        ], [
            'city' => 'App\\Entity\\City',
            'util' => 'App\\Service\\WeatherUtil',
        ]);
    }
}
