<?php

namespace Container0xEe0U7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherCountryCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\WeatherCountryCommand' shared autowired service.
     *
     * @return \App\Command\WeatherCountryCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'WeatherCountryCommand.php';

        $container->privates['App\\Command\\WeatherCountryCommand'] = $instance = new \App\Command\WeatherCountryCommand(($container->privates['App\\Service\\WeatherUtil'] ?? $container->load('getWeatherUtilService')));

        $instance->setName('weather:country');
        $instance->setDescription('Displays a forecast for selected city in a selected country');

        return $instance;
    }
}
