<?php

namespace ContainerGHwx8LF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AySNhdqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AySNhdq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AySNhdq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'forecast' => ['privates', '.errored..service_locator.AySNhdq.App\\Entity\\Forecast', NULL, 'Cannot autowire service ".service_locator.AySNhdq": it needs an instance of "App\\Entity\\Forecast" but this type has been excluded in "config/services.yaml".'],
        ], [
            'forecast' => 'App\\Entity\\Forecast',
        ]);
    }
}
