<?php

namespace ContainerJmu4BJH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xb99AQHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xb99AQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xb99AQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'city' => ['privates', '.errored..service_locator.Xb99AQH.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.Xb99AQH": it needs an instance of "App\\Entity\\City" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\ForecastRepository', 'getForecastRepositoryService', true],
        ], [
            'city' => 'App\\Entity\\City',
            'repository' => 'App\\Repository\\ForecastRepository',
        ]);
    }
}
