<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNDmPtWg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNDmPtWg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNDmPtWg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNDmPtWg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNDmPtWg\App_KernelDevDebugContainer([
    'container.build_hash' => 'NDmPtWg',
    'container.build_id' => '6b00350c',
    'container.build_time' => 1728486343,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNDmPtWg');
