<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xEe0U7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xEe0U7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xEe0U7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xEe0U7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xEe0U7\App_KernelDevDebugContainer([
    'container.build_hash' => '0xEe0U7',
    'container.build_id' => 'cbd289dc',
    'container.build_time' => 1729690150,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xEe0U7');
