<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBtA4xIF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBtA4xIF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBtA4xIF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBtA4xIF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBtA4xIF\App_KernelDevDebugContainer([
    'container.build_hash' => 'BtA4xIF',
    'container.build_id' => '3f598773',
    'container.build_time' => 1729477116,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBtA4xIF');
